<x-warehouse-layout title="Add Cattle">
<div class="mx-auto max-w-5xl overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b px-5 py-5 sm:px-7"><div><h1 class="m-0 text-xl font-extrabold">Add Cattle</h1><p class="mb-0 mt-1 text-sm text-slate-500">Add cattle information for one of your farms.</p></div><a href="{{ route('warehouse.cattle') }}" class="rounded-xl border border-slate-300 px-4 py-2 text-sm font-bold text-slate-700">← Back</a></div>
<form method="POST" action="{{ route('warehouse.cattle.store') }}" class="space-y-7 p-5 sm:p-7">@csrf
<section><h2 class="border-b-2 border-emerald-500 pb-2 text-base font-extrabold text-emerald-700">Basic Info</h2><div class="mt-5 grid gap-5 md:grid-cols-2"><div><x-warehouse.searchable-select name="farm_id" id="cattle-create-farm" label="Farm *" :options="$options['farms']" :selected="old('farm_id')" placeholder="Select Farm" search-placeholder="Search farm" required /></div>@foreach([['tag','Tag'],['name','Name']] as [$field,$label])<div><label class="mb-2 block text-sm font-semibold text-slate-700">{{ $label }} *</label><input name="{{ $field }}" value="{{ old($field) }}" required class="h-11 w-full rounded-xl border border-slate-300 px-3 text-sm" placeholder="{{ $label }}"></div>@endforeach
@foreach([['cattle_group_id','Group',$options['groups']],['cattle_breed_id','Breed',$options['breeds']],['birth_date','Birth Date',null],['weight','Weight',null],['gender','Gender',['গাভী'=>'গাভী','দামড়া'=>'দামড়া']],['health_problem','Health Problem',['হ্যাঁ'=>'হ্যাঁ','না'=>'না']]] as [$field,$label,$values])<div><label class="mb-2 block text-sm font-semibold text-slate-700">{{ $label }} *</label>@if($values)<select name="{{ $field }}" required class="h-11 w-full rounded-xl border border-slate-300 px-3 text-sm"><option value="">Select</option>@foreach($values as $id=>$value)<option value="{{ $id }}" @selected(old($field)==$id)>{{ $value }}</option>@endforeach</select>@else<input name="{{ $field }}" value="{{ old($field) }}" type="{{ $field==='birth_date'?'date':'text' }}" required class="h-11 w-full rounded-xl border border-slate-300 px-3 text-sm" placeholder="{{ $label }}">@endif</div>@endforeach</div></section>
<section><h2 class="border-b-2 border-emerald-500 pb-2 text-base font-extrabold text-emerald-700">Milk, Reproduction, Disease Info</h2><div class="mt-5 grid gap-5 md:grid-cols-2"><x-warehouse.searchable-select name="avg_milk_production" id="cattle-avg-milk-production" label="Average Milk Production (Litre)" :options="collect(range(1, 34))->mapWithKeys(fn($number) => [$number => $number])" :selected="old('avg_milk_production')" placeholder="Select litre" search-placeholder="Search litre" /><x-warehouse.searchable-select name="milk_production_status" id="cattle-milk-production-status" label="Milk Production Status" :options="['হ্যা' => 'হ্যা', 'না' => 'না']" :selected="old('milk_production_status')" placeholder="Select status" search-placeholder="Search status" /><x-warehouse.searchable-select name="calf_count" id="cattle-calf-count" label="Calf Birth Count" :options="collect(range(0, 9))->mapWithKeys(fn($number) => [$number => $number])" :selected="old('calf_count')" placeholder="Select calf birth count" search-placeholder="Search count" /><div><label class="mb-2 block text-sm font-semibold text-slate-700">Last Calf Birth Date</label><input name="last_calf_birth_date" value="{{ old('last_calf_birth_date') }}" type="date" class="h-11 w-full rounded-xl border border-slate-300 px-3 text-sm"></div><x-warehouse.searchable-select name="genetic_percentage" id="cattle-genetic-percentage" label="Genetic Percentage" :options="collect([50,55,60,65,70,75,80,85,'87.5',100])->mapWithKeys(fn($number) => [(string) $number => (string) $number])" :selected="old('genetic_percentage')" placeholder="Select genetic percentage" search-placeholder="Search percentage" /></div></section>
<section><h2 class="border-b-2 border-emerald-500 pb-2 text-base font-extrabold text-emerald-700">Ancestral Disease Info</h2><div class="relative mt-4" data-multi-select><button type="button" class="flex h-11 w-full items-center justify-between rounded-xl border border-slate-300 bg-white px-4 text-left text-sm" data-multi-toggle><span data-multi-label>Select disease history</span><span>⌄</span></button><div class="absolute z-30 mt-2 hidden w-full rounded-xl border border-slate-200 bg-white p-3 shadow-xl" data-multi-panel><input type="search" placeholder="Search disease history" class="h-10 w-full rounded-lg border border-slate-300 px-3 text-sm" data-multi-search><div class="mt-2 max-h-52 space-y-1 overflow-y-auto">@foreach($options['diseaseHistories'] as $id=>$name)<label class="flex cursor-pointer items-center gap-3 rounded-lg px-3 py-2 text-sm hover:bg-emerald-50" data-multi-option data-name="{{ Str::lower($name) }}"><input type="checkbox" name="disease_history_ids[]" value="{{ $id }}" @checked(in_array($id, old('disease_history_ids', []))) class="h-4 w-4 rounded border-slate-300 text-emerald-600">{{ $name }}</label>@endforeach</div></div></div></section>
<section><h2 class="border-b-2 border-emerald-500 pb-2 text-base font-extrabold text-emerald-700">Reproductive Health Info</h2><div class="relative mt-4" data-multi-select><button type="button" class="flex h-11 w-full items-center justify-between rounded-xl border border-slate-300 bg-white px-4 text-left text-sm" data-multi-toggle><span data-multi-label>Select reproductive health information</span><span>⌄</span></button><div class="absolute z-30 mt-2 hidden w-full rounded-xl border border-slate-200 bg-white p-3 shadow-xl" data-multi-panel><input type="search" placeholder="Search health information" class="h-10 w-full rounded-lg border border-slate-300 px-3 text-sm" data-multi-search><div class="mt-2 max-h-52 space-y-1 overflow-y-auto">@foreach($options['healthInfos'] as $id=>$name)<label class="flex cursor-pointer items-center gap-3 rounded-lg px-3 py-2 text-sm hover:bg-emerald-50" data-multi-option data-name="{{ Str::lower($name) }}"><input type="checkbox" name="health_info_ids[]" value="{{ $id }}" @checked(in_array($id, old('health_info_ids', []))) class="h-4 w-4 rounded border-slate-300 text-emerald-600">{{ $name }}</label>@endforeach</div></div></div></section>
<section><h2 class="border-b-2 border-emerald-500 pb-2 text-base font-extrabold text-emerald-700">Insurance Info</h2><div class="mt-5 grid gap-5 md:grid-cols-2">@foreach([['insurance_company_id','Insurance Company',$options['companies']],['insurance_type_id','Insurance Type',$options['types']]] as [$field,$label,$values])<div><label class="mb-2 block text-sm font-semibold text-slate-700">{{ $label }} *</label><select name="{{ $field }}" required class="h-11 w-full rounded-xl border border-slate-300 px-3 text-sm"><option value="">Select</option>@foreach($values as $id=>$value)<option value="{{ $id }}" @selected(old($field)==$id)>{{ $value }}</option>@endforeach</select></div>@endforeach<div><label class="mb-2 block text-sm font-semibold text-slate-700">Insurance No *</label><input name="insurance_no" value="{{ old('insurance_no') }}" required class="h-11 w-full rounded-xl border border-slate-300 px-3 text-sm"></div></div></section>
<div class="flex justify-end gap-3 border-t pt-5"><a href="{{ route('warehouse.cattle') }}" class="rounded-xl border border-slate-300 px-5 py-3 text-sm font-bold text-slate-700">Cancel</a><button class="rounded-xl bg-emerald-600 px-6 py-3 text-sm font-bold text-white">Save Cattle</button></div></form></div>
<script>
    document.querySelectorAll('[data-multi-select]').forEach(select => {
        const toggle = select.querySelector('[data-multi-toggle]');
        const panel = select.querySelector('[data-multi-panel]');
        const search = select.querySelector('[data-multi-search]');
        const label = select.querySelector('[data-multi-label]');
        const refreshLabel = () => {
            const checked = [...select.querySelectorAll('input[type="checkbox"]:checked')].map(input => input.closest('label').textContent.trim());
            label.textContent = checked.length ? checked.join(', ') : (label.dataset.placeholder || label.textContent);
        };
        label.dataset.placeholder = label.textContent;
        refreshLabel();
        toggle.addEventListener('click', () => panel.classList.toggle('hidden'));
        search.addEventListener('input', () => {
            const query = search.value.trim().toLowerCase();
            select.querySelectorAll('[data-multi-option]').forEach(option => option.classList.toggle('hidden', !option.dataset.name.toLowerCase().includes(query)));
        });
        select.querySelectorAll('input[type="checkbox"]').forEach(input => input.addEventListener('change', refreshLabel));
        document.addEventListener('click', event => { if (!select.contains(event.target)) panel.classList.add('hidden'); });
    });
</script>
<script>document.querySelector('form[action="{{ route('warehouse.cattle.store') }}"]')?.addEventListener('submit', function () { if (!this.checkValidity()) return; const button=this.querySelector('button[type="submit"], button:not([type])'); if (!button || button.disabled) return; button.disabled=true; button.innerHTML='<span class="mr-2 inline-block h-4 w-4 animate-spin rounded-full border-2 border-white border-t-transparent align-[-2px]"></span> Saving...'; });</script>
</x-warehouse-layout>
