<x-warehouse-layout title="Farm">
<div class="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">
<div class="flex items-center justify-between border-b px-5 py-5"><div><h1 class="m-0 text-xl font-extrabold">Farm</h1><p class="mb-0 mt-1 text-sm text-slate-500">Manage farms belonging to your customers.</p></div><button id="open-farm-modal" type="button" class="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-bold text-white">+ Add Farm</button></div>
@if(session('message'))<div class="m-4 rounded-xl bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{{ session('message') }}</div>@endif
<form method="GET" class="border-b bg-slate-50 p-4"><div class="flex flex-col gap-3 sm:flex-row"><select name="per_page" class="h-11 rounded-xl border bg-white px-3 text-sm"><option value="10" @selected($perPage === '10')>10</option><option value="25" @selected($perPage === '25')>25</option><option value="50" @selected($perPage === '50')>50</option><option value="100" @selected($perPage === '100')>100</option></select><input name="search" value="{{ $search }}" placeholder="Search customer or farm name" class="h-11 flex-1 rounded-xl border px-4 text-sm"><button class="rounded-xl bg-emerald-600 px-5 text-sm font-semibold text-white">Search</button><a href="{{ route('warehouse.farms') }}" class="rounded-xl border px-5 py-3 text-center text-sm font-semibold">Reset</a></div></form>
<div class="overflow-x-auto"><table class="min-w-[620px] w-full text-left text-sm"><thead class="bg-emerald-700 text-xs font-bold uppercase text-white"><tr><th class="px-5 py-3">SL</th><th class="px-5 py-3">Customer</th><th class="px-5 py-3">Farm Name</th><th class="px-5 py-3">Actions</th></tr></thead><tbody class="divide-y">@forelse($farms as $farm)<tr><td class="px-5 py-3">{{ $farms->firstItem()+$loop->index }}</td><td class="px-5 py-3 font-semibold">{{ $farm->customer?->name ?: '-' }}<div class="text-xs font-normal text-slate-400">{{ $farm->customer?->mobile ?: 'No Number' }}</div></td><td class="px-5 py-3">{{ $farm->name ?: '-' }}</td><td class="px-5 py-3"><div class="flex gap-2"><button type="button" class="edit-farm rounded-lg border border-blue-200 px-3 py-1.5 text-xs font-bold text-blue-700" data-farm="{{ e(json_encode(['id'=>$farm->id,'app_customer_id'=>$farm->app_customer_id,'name'=>$farm->name,'division_id'=>$farm->division_id,'district_id'=>$farm->district_id,'upazila_id'=>$farm->upazila_id,'union_id'=>$farm->union_id])) }}">Edit</button><form method="POST" action="{{ route('warehouse.farms.destroy',$farm) }}" onsubmit="return confirm('Delete this farm?')">@csrf @method('DELETE')<button class="rounded-lg border border-red-200 px-3 py-1.5 text-xs font-bold text-red-700">Delete</button></form></div></td></tr>@empty<tr><td colspan="4" class="px-5 py-12 text-center text-slate-500">No farm records found.</td></tr>@endforelse</tbody></table></div><div class="border-t px-4 py-4">{{ $farms->onEachSide(1)->links('warehouse-portal.partials.pagination') }}</div></div>
<div id="farm-modal" class="fixed inset-0 z-50 hidden items-center justify-center bg-slate-900/60 p-4"><div class="max-h-[95vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white shadow-2xl"><div class="flex items-center justify-between border-b px-5 py-4"><h2 id="farm-modal-title" class="m-0 text-lg font-extrabold">Add Farm</h2><button type="button" id="close-farm-modal" class="text-2xl text-slate-400">&times;</button></div><form id="farm-form" method="POST" action="{{ route('warehouse.farms.store') }}" class="space-y-4 p-5">@csrf<input type="hidden" name="_method" id="farm-method"><div class="flex items-end gap-2"><div class="min-w-0 flex-1"><x-warehouse.searchable-select name="app_customer_id" id="farm-customer" label="Customer *" :options="$customers->mapWithKeys(fn($c) => [$c->id => $c->name.' ('.($c->mobile ?: 'No Number').')'])" placeholder="Select Customer" search-placeholder="Search customer" required /></div><a href="{{ route('warehouse.beneficiaries.create') }}" target="_blank" class="mb-0 inline-flex h-11 w-11 items-center justify-center rounded-xl bg-emerald-600 text-2xl font-bold text-white">+</a></div><div><label class="mb-1 block text-sm font-semibold">Name <span class="text-red-500">*</span></label><input name="name" id="farm-name" required class="h-11 w-full rounded-xl border px-3 text-sm" placeholder="Farm name"></div><div class="grid gap-4 sm:grid-cols-2"><x-warehouse.searchable-select name="division_id" id="farm-division" label="Division" :options="$divisions" placeholder="Select Division" search-placeholder="Search division" /><x-warehouse.searchable-select name="district_id" id="farm-district" label="District" placeholder="Select District" search-placeholder="Search district" /><x-warehouse.searchable-select name="upazila_id" id="farm-upazila" label="Thana" placeholder="Select Thana" search-placeholder="Search thana" /><x-warehouse.searchable-select name="union_id" id="farm-union" label="Union" placeholder="Select Union" search-placeholder="Search union" /></div><div class="flex justify-end gap-2 border-t pt-4"><button type="button" id="cancel-farm-modal" class="rounded-xl border px-4 py-2 text-sm font-bold">Close</button><button class="rounded-xl bg-emerald-600 px-5 py-2 text-sm font-bold text-white">Save</button></div></form></div></div>
<script>
window.addEventListener('warehouse-searchable-select-change', async function farmLocationLoader(event) { const { id, value } = event.detail; const base = { 'farm-division': '/warehouse/renewable-energy/geocode/districts/', 'farm-district': '/warehouse/renewable-energy/geocode/upazilas/', 'farm-upazila': '/warehouse/renewable-energy/geocode/unions/' }; const target = { 'farm-division': 'farm-district', 'farm-district': 'farm-upazila', 'farm-upazila': 'farm-union' }[id]; if (!base[id]) return; event.stopImmediatePropagation(); if (!value) return; const response = await fetch(base[id] + encodeURIComponent(value), { headers: { Accept: 'application/json' } }); const items = await response.json(); window.dispatchEvent(new CustomEvent('warehouse-searchable-select-options', { detail: { id: target, options: items.map(item => ({ value: String(item.id), label: item.name })), selected: '' } })); }, true);
(()=>{const modal=document.getElementById('farm-modal'),form=document.getElementById('farm-form'),method=document.getElementById('farm-method'),customer='farm-customer',name=document.getElementById('farm-name'),fields={division:'farm-division',district:'farm-district',upazila:'farm-upazila',union:'farm-union'},store=@json(route('warehouse.farms.store')),update=@json(route('warehouse.farms.update',['farm'=>'__FARM__'])),urls={district:@json(route('warehouse.renewable-energy.districts',['division'=>'__ID__'])),upazila:@json(route('warehouse.renewable-energy.upazilas',['district'=>'__ID__'])),union:@json(route('warehouse.renewable-energy.unions',['upazila'=>'__ID__']))};const set=(id,items,selected='')=>document.dispatchEvent(new CustomEvent('warehouse-searchable-select-options',{detail:{id,options:items.map(x=>({value:String(x.id),label:x.name})),selected}}));const load=async(id,url,selected='')=>{if(!url)return set(id,[],selected);const r=await fetch(url,{headers:{Accept:'application/json'}});set(id,await r.json(),selected)};const val=id=>document.getElementById(id)?.querySelector('input[type=hidden]')?.value||'';const reset=id=>set(id,[]);const open=async d=>{form.reset();method.value='';form.action=store;Object.values(fields).forEach(reset);document.getElementById('farm-modal-title').textContent=d?'Edit Farm':'Add Farm';if(d){form.action=update.replace('__FARM__',d.id);method.value='PUT';set(customer,@json($customers->map(fn($c)=>['id'=>$c->id,'name'=>$c->name.' ('.($c->mobile ?: 'No Number').')'])->values()),d.app_customer_id);name.value=d.name||'';set(fields.division,@json($divisions->map(fn($n,$id)=>['id'=>$id,'name'=>$n])->values()),d.division_id);await load(fields.district,d.division_id?urls.district.replace('__ID__',d.division_id):'',d.district_id);await load(fields.upazila,d.district_id?urls.upazila.replace('__ID__',d.district_id):'',d.upazila_id);await load(fields.union,d.upazila_id?urls.union.replace('__ID__',d.upazila_id):'',d.union_id)}modal.classList.remove('hidden');modal.classList.add('flex')};const close=()=>{modal.classList.add('hidden');modal.classList.remove('flex')};window.addEventListener('warehouse-searchable-select-change',async e=>{const {id,value}=e.detail;if(id===fields.division){reset(fields.district);reset(fields.upazila);reset(fields.union);await load(fields.district,value?urls.district.replace('__ID__',value):'')}if(id===fields.district){reset(fields.upazila);reset(fields.union);await load(fields.upazila,value?urls.upazila.replace('__ID__',value):'')}if(id===fields.upazila)await load(fields.union,value?urls.union.replace('__ID__',value):'')});document.getElementById('open-farm-modal').onclick=()=>open();document.getElementById('close-farm-modal').onclick=close;document.getElementById('cancel-farm-modal').onclick=close;modal.onclick=e=>{if(e.target===modal)close()};document.querySelectorAll('.edit-farm').forEach(b=>b.onclick=()=>open(JSON.parse(b.dataset.farm)))})();
</script>
<style>
    /* Let searchable dropdowns extend over the modal while the modal itself scrolls. */
    #farm-modal { align-items: flex-start; overflow-y: auto; }
    #farm-modal > div { max-height: none !important; margin: 1rem auto; overflow: visible !important; }
    #farm-modal [x-show] { z-index: 200 !important; }
    #farm-modal [x-show] > div.max-h-64 { overflow-y: auto !important; }
</style>
<script>document.getElementById('farm-form')?.addEventListener('submit', function () { if (!this.checkValidity()) return; const button=this.querySelector('button[type="submit"], button:not([type])'); if (!button || button.disabled) return; button.disabled=true; button.innerHTML='<span class="mr-2 inline-block h-4 w-4 animate-spin rounded-full border-2 border-white border-t-transparent align-[-2px]"></span> Saving...'; });</script>
</x-warehouse-layout>
