<x-warehouse-layout title="Visit Details">
    <div class="space-y-5">
        <x-warehouse.hero-header eyebrow="Daily Visit" title="Visit Details" description="Complete information for this beneficiary visit." :back-href="route('warehouse.daily-visits')" back-label="Back to Visit List" />
        @if($isSalesman ?? false)<div class="flex justify-end"><x-warehouse.button href="{{ route('warehouse.daily-visits.edit', $visit) }}" variant="secondary" class="border-sky-200 bg-sky-50 text-sky-700 hover:bg-sky-100">Edit Visit</x-warehouse.button></div>@endif
        <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            <div class="rounded-2xl border border-blue-200 bg-blue-50 p-5"><p class="m-0 text-xs font-bold uppercase tracking-wider text-blue-700">Visit Date &amp; Time</p><p class="mb-0 mt-3 text-lg font-extrabold text-slate-900">{{ $visit->visit_date?->format('d M Y') ?: '-' }}</p><p class="mb-0 mt-1 text-sm font-medium text-blue-700">{{ $visit->created_at?->format('h:i A') ?: '-' }}</p></div>
            <div class="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><p class="m-0 text-xs font-bold uppercase tracking-wider text-emerald-700">Total Fees</p><p class="mb-0 mt-3 text-2xl font-extrabold text-emerald-900">{{ $visit->fees->isNotEmpty() ? number_format((float) $visit->fees->sum('amount'), 2) : '-' }}</p><p class="mb-0 mt-1 text-sm font-medium text-emerald-700">{{ $visit->fees->isNotEmpty() ? 'BDT' : 'No fee recorded' }}</p></div>
            <div class="rounded-2xl border border-violet-200 bg-violet-50 p-5"><p class="m-0 text-xs font-bold uppercase tracking-wider text-violet-700">Visit Type</p><p class="mb-0 mt-3 text-lg font-extrabold text-slate-900">{{ $visit->visit_type ?: '-' }}</p><p class="mb-0 mt-1 text-sm text-violet-700">Recorded visit</p></div>
            <div class="rounded-2xl border border-amber-200 bg-amber-50 p-5"><p class="m-0 text-xs font-bold uppercase tracking-wider text-amber-700">Memo Number</p><p class="mb-0 mt-3 truncate text-lg font-extrabold text-slate-900">{{ is_array($visit->memo_no) && count($visit->memo_no) ? implode(', ', $visit->memo_no) : '-' }}</p><p class="mb-0 mt-1 text-sm text-amber-700">Invoice / reference</p></div>
        </div>
        <div class="grid gap-5 lg:grid-cols-[minmax(0,1.1fr)_minmax(320px,.9fr)]">
            <section class="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 px-5 py-4 sm:px-6"><h2 class="m-0 text-base font-extrabold text-slate-900">Beneficiary Information</h2><p class="mb-0 mt-1 text-sm text-slate-500">Customer and visit reference details</p></div><div class="grid gap-5 p-5 sm:grid-cols-2 sm:p-6"><div><p class="m-0 text-xs font-bold uppercase tracking-wider text-slate-400">Beneficiary Name</p><p class="mb-0 mt-2 text-sm font-bold text-slate-900">{{ $visit->appCustomer?->name ?: '-' }}</p></div><div><p class="m-0 text-xs font-bold uppercase tracking-wider text-slate-400">Cell Number</p><p class="mb-0 mt-2 text-sm font-semibold text-slate-700">{{ $visit->appCustomer?->mobile ?: $visit->customer_number ?: '-' }}</p></div><div><p class="m-0 text-xs font-bold uppercase tracking-wider text-slate-400">Beneficiary Number</p><p class="mb-0 mt-2 text-sm font-semibold text-slate-700">{{ $visit->beneficiary_number ?: '-' }}</p></div><div><p class="m-0 text-xs font-bold uppercase tracking-wider text-slate-400">Group Number</p><p class="mb-0 mt-2 text-sm font-semibold text-slate-700">{{ $visit->appCustomer?->group_number ?: '-' }}</p></div></div><div class="border-t border-slate-100 px-5 py-5 sm:px-6"><p class="m-0 text-xs font-bold uppercase tracking-wider text-slate-400">Description</p><p class="mb-0 mt-2 whitespace-pre-line text-sm leading-6 text-slate-700">{{ $visit->description ?: 'No description was added for this visit.' }}</p></div></section>
            <section class="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 px-5 py-4 sm:px-6"><h2 class="m-0 text-base font-extrabold text-slate-900">Visit Summary</h2><p class="mb-0 mt-1 text-sm text-slate-500">Assigned LSP and fee details</p></div><div class="space-y-5 p-5 sm:p-6"><div class="rounded-2xl border border-emerald-100 bg-emerald-50 px-4 py-3"><p class="m-0 text-xs font-bold uppercase tracking-wider text-emerald-700">LSP</p><p class="mb-0 mt-1 text-base font-extrabold text-emerald-950">{{ $visit->agent?->employee_name ?: $visit->agent?->name ?: '-' }}</p></div><div><p class="m-0 text-xs font-bold uppercase tracking-wider text-slate-400">Fee Breakdown</p><div class="mt-3 overflow-hidden rounded-xl border border-slate-200"><table class="w-full text-sm"><tbody class="divide-y divide-slate-100">@forelse($visit->fees as $fee)<tr><td class="px-3 py-3 text-slate-600">{{ $fee->fee_type ?: '-' }}</td><td class="px-3 py-3 text-right font-bold text-slate-900">{{ number_format((float) $fee->amount, 2) }} BDT</td></tr>@empty<tr><td colspan="2" class="px-3 py-4 text-slate-400">No fees recorded.</td></tr>@endforelse</tbody><tfoot><tr class="border-t-2 border-slate-200 bg-slate-50"><th class="px-3 py-3 text-right font-bold text-slate-700">Total</th><th class="px-3 py-3 text-right font-extrabold text-slate-900">{{ number_format((float) $visit->fees->sum('amount'), 2) }} BDT</th></tr></tfoot></table></div></div></div></section>
        </div>
    </div>
</x-warehouse-layout>
