<x-warehouse-layout title="Add Renewable Energy Entry">
    <div class="mx-auto max-w-6xl overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">
        <x-warehouse.page-header title="Add Renewable Energy Entry" description="Visit date is recorded automatically as today."><x-slot name="actions"><x-warehouse.button href="{{ route('warehouse.renewable-energy.index') }}" variant="secondary" icon="arrow-left">Back to List</x-warehouse.button></x-slot></x-warehouse.page-header>
        <form method="POST" action="{{ route('warehouse.renewable-energy.store') }}" enctype="multipart/form-data" class="space-y-6 p-5 sm:p-7">@csrf
            <div class="grid gap-5 md:grid-cols-2"><div><x-warehouse.input-label for="type" value="Energy Type *" class="mb-2" /><select id="type" name="type" required class="block w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm"><option value="">Select Type</option><option value="biogas" @selected(old('type') === 'biogas')>Biogas</option><option value="solar" @selected(old('type') === 'solar')>Solar</option></select></div><div><x-warehouse.input-label value="Visit Date" class="mb-2" /><input value="{{ now()->format('d M, Y') }}" readonly class="block w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-500"></div><div><x-warehouse.input-label value="Area Office" class="mb-2" /><input value="{{ $warehouse->name }}" readonly class="block w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-600"></div><div><x-warehouse.input-label value="LSP Name" class="mb-2" /><input value="{{ $warehouseName }}" readonly class="block w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-600"></div></div>
            <div class="border-t border-slate-200 pt-6"><h2 class="m-0 text-lg font-bold text-slate-900">Client Information</h2><div class="mt-5 grid gap-5 md:grid-cols-2"><div><x-warehouse.input-label for="client_name" value="Client Name *" class="mb-2" /><input id="client_name" name="client_name" value="{{ old('client_name') }}" required class="block w-full rounded-xl border border-slate-300 px-4 py-3 text-sm"></div>
            <div><x-warehouse.input-label for="client_number" value="Client Number" class="mb-2" /><input id="client_number" name="client_number" value="{{ old('client_number') }}" class="block w-full rounded-xl border border-slate-300 px-4 py-3 text-sm"></div><div><x-warehouse.searchable-select name="division_id" id="division_id" label="Division" :options="$divisions" :selected="old('division_id')" placeholder="Select Division" search-placeholder="Search division" /></div>
       <div><x-warehouse.searchable-select name="district_id" id="district_id" label="District" placeholder="Select District" search-placeholder="Search district" /></div><div><x-warehouse.searchable-select name="upazila_id" id="upazila_id" label="Upazila" placeholder="Select Upazila" search-placeholder="Search upazila" /></div><div><x-warehouse.searchable-select name="union_id" id="union_id" label="Union" placeholder="Select Union" search-placeholder="Search union"/> <div><x-warehouse.input-label for="ward_number" value="Ward Number" class="mb-2" /><input id="ward_number" name="ward_number" value="{{ old('ward_number') }}" class="block w-full rounded-xl border border-slate-300 px-4 py-3 text-sm"></div><div><x-warehouse.input-label for="village" value="Village" class="mb-2" /><input id="village" name="village" value="{{ old('village') }}" class="block w-full rounded-xl border border-slate-300 px-4 py-3 text-sm"></div><div><x-warehouse.input-label for="po_name" value="P.O Name" class="mb-2" /><input id="po_name" name="po_name" value="{{ old('po_name') }}" class="block w-full rounded-xl border border-slate-300 px-4 py-3 text-sm"></div></div></div>
            
       
            
            
           
            <div class="border-t border-slate-200 pt-6"><h2 class="m-0 text-lg font-bold text-slate-900">Technical Details</h2><div class="mt-5 grid gap-5 md:grid-cols-3"><div><x-warehouse.input-label for="plant_size" value="Plant Size" class="mb-2" /><input id="plant_size" type="number" min="0" step="0.01" name="plant_size" value="{{ old('plant_size') }}" class="block w-full rounded-xl border border-slate-300 px-4 py-3 text-sm"></div><div><x-warehouse.input-label for="plant_size_unit" value="Plant Size Unit" class="mb-2" /><input id="plant_size_unit" name="plant_size_unit" value="{{ old('plant_size_unit', 'm³') }}" class="block w-full rounded-xl border border-slate-300 px-4 py-3 text-sm"></div><div><x-warehouse.input-label for="livestock_details" value="Livestock Details (for Biogas)" class="mb-2" /><input id="livestock_details" name="livestock_details" value="{{ old('livestock_details') }}" class="block w-full rounded-xl border border-slate-300 px-4 py-3 text-sm"></div><div><x-warehouse.input-label for="plant_start_date" value="Plant Start Date" class="mb-2" /><input id="plant_start_date" type="date" name="plant_start_date" value="{{ old('plant_start_date') }}" class="block w-full rounded-xl border border-slate-300 px-4 py-3 text-sm"></div><div><x-warehouse.input-label for="plant_end_date" value="Plant End Date" class="mb-2" /><input id="plant_end_date" type="date" name="plant_end_date" value="{{ old('plant_end_date') }}" class="block w-full rounded-xl border border-slate-300 px-4 py-3 text-sm"></div><div><x-warehouse.input-label for="document" value="Document / File (Max 10MB)" class="mb-2" /><input id="document" type="file" name="document" accept="image/*,.pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.txt,.zip,.rar" class="block w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm"></div></div><div class="mt-5"><x-warehouse.input-label for="contribution_condition" value="Plant Contribution / Condition" class="mb-2" /><textarea id="contribution_condition" name="contribution_condition" rows="3" class="block w-full rounded-xl border border-slate-300 px-4 py-3 text-sm">{{ old('contribution_condition') }}</textarea></div><div class="mt-5"><x-warehouse.input-label for="remarks" value="Remarks" class="mb-2" /><textarea id="remarks" name="remarks" rows="3" class="block w-full rounded-xl border border-slate-300 px-4 py-3 text-sm">{{ old('remarks') }}</textarea></div></div>
            <div class="flex justify-end"><x-loading-submit type="submit" class="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-600 px-5 py-3 text-sm font-semibold text-white shadow-sm hover:bg-emerald-500" icon="save" loading-text="Saving...">Save Entry</x-loading-submit></div>
        </form>
    </div>
    <script>
        const setOptions = (id, items) => window.dispatchEvent(new CustomEvent('warehouse-searchable-select-options', { detail: { id, options: (Array.isArray(items) ? items : []).map(item => ({ value: String(item.id), label: item.en_name || item.name })) } }));
        const loadOptions = async (id, url) => {
            if (!url) return setOptions(id, []);
            const response = await fetch(url, { headers: { 'Accept': 'application/json' } });
            if (!response.ok) return setOptions(id, []);
            const payload = await response.json();
            setOptions(id, payload.data || payload);
        };
        window.addEventListener('warehouse-searchable-select-change', async event => { const { id, value } = event.detail; if (id === 'division_id') { await loadOptions('district_id', value ? `{{ url('/warehouse/renewable-energy/geocode/districts') }}/${value}` : null); setOptions('upazila_id', []); setOptions('union_id', []); } if (id === 'district_id') { await loadOptions('upazila_id', value ? `{{ url('/warehouse/renewable-energy/geocode/upazilas') }}/${value}` : null); setOptions('union_id', []); } if (id === 'upazila_id') await loadOptions('union_id', value ? `{{ url('/warehouse/renewable-energy/geocode/unions') }}/${value}` : null); });
    </script>
</x-warehouse-layout>
