<x-warehouse-layout title="Edit Renewable Energy Entry">
<div class="mx-auto max-w-6xl overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><x-warehouse.page-header title="Edit Renewable Energy Entry" description="Update all renewable energy entry information."><x-slot name="actions"><x-warehouse.button href="{{ route('warehouse.renewable-energy.index') }}" variant="secondary" icon="arrow-left">Back to List</x-warehouse.button></x-slot></x-warehouse.page-header>
<form method="POST" action="{{ route('warehouse.renewable-energy.update', $renewableEnergy) }}" enctype="multipart/form-data" class="space-y-6 p-5 sm:p-7">@csrf @method('PUT')
<div class="grid gap-5 md:grid-cols-2"><div><x-warehouse.input-label for="type" value="Energy Type *" class="mb-2"/><select id="type" name="type" required class="block w-full rounded-xl border p-3"><option value="biogas" {{ old('type', $renewableEnergy->type) === 'biogas' ? 'selected' : '' }}>Biogas</option><option value="solar" {{ old('type', $renewableEnergy->type) === 'solar' ? 'selected' : '' }}>Solar</option></select></div><div><x-warehouse.input-label value="Visit Date" class="mb-2"/><input value="{{ $renewableEnergy->visit_date ? \Carbon\Carbon::parse($renewableEnergy->visit_date)->format('d M, Y') : '-' }}" readonly class="block w-full rounded-xl border bg-slate-50 p-3"></div><div><x-warehouse.input-label value="Warehouse" class="mb-2"/><input value="{{ $warehouse->name }}" readonly class="block w-full rounded-xl border bg-slate-50 p-3"></div></div>
<div class="border-t pt-6"><h2 class="text-lg font-bold">Client Information</h2><div class="mt-5 grid gap-5 md:grid-cols-2"><div><x-warehouse.input-label for="client_name" value="Client Name *" class="mb-2"/><input id="client_name" name="client_name" required value="{{ old('client_name',$renewableEnergy->client_name) }}" class="block w-full rounded-xl border p-3"></div><div><x-warehouse.input-label for="client_number" value="Client Number" class="mb-2"/><input id="client_number" name="client_number" value="{{ old('client_number',$renewableEnergy->client_number) }}" class="block w-full rounded-xl border p-3"></div><div><x-warehouse.searchable-select name="division_id" id="division_id" label="Division" :options="$divisions" :selected="old('division_id',$renewableEnergy->division_id)" placeholder="Select Division" search-placeholder="Search division"/></div><div><x-warehouse.searchable-select name="district_id" id="district_id" label="District" :options="$districts" :selected="old('district_id',$renewableEnergy->district_id)" placeholder="Select District" search-placeholder="Search district"/></div><div><x-warehouse.searchable-select name="upazila_id" id="upazila_id" label="Upazila" :options="$upazilas" :selected="old('upazila_id',$renewableEnergy->upazila_id)" placeholder="Select Upazila" search-placeholder="Search upazila"/></div><div><x-warehouse.searchable-select name="union_id" id="union_id" label="Union" :options="$unions" :selected="old('union_id',$renewableEnergy->union_id)" placeholder="Select Union" search-placeholder="Search union"/></div><div><x-warehouse.input-label for="ward_number" value="Ward Number" class="mb-2"/><select id="ward_number" name="ward_number" class="block w-full rounded-xl border p-3"><option value="">Select Ward Number</option>@foreach(range(1, 20) as $number)<option value="{{ $number }}" @selected((string) old('ward_number', $renewableEnergy->ward_number) === (string) $number)>{{ $number }}</option>@endforeach</select></div><div><x-warehouse.input-label for="village" value="Village" class="mb-2"/><input id="village" name="village" value="{{ old('village',$renewableEnergy->village) }}" class="block w-full rounded-xl border p-3"></div><div><x-warehouse.input-label for="po_name" value="P.O Name" class="mb-2"/><input id="po_name" name="po_name" value="{{ old('po_name',$renewableEnergy->po_name) }}" class="block w-full rounded-xl border p-3"></div></div></div>
<div class="border-t pt-6"><h2 class="text-lg font-bold">Technical Details</h2><div class="mt-5 grid gap-5 md:grid-cols-3"><div><x-warehouse.input-label for="plant_size" value="Plant Size" class="mb-2"/><input id="plant_size" name="plant_size" type="number" step="0.01" min="0" value="{{ old('plant_size',$renewableEnergy->plant_size) }}" class="block w-full rounded-xl border p-3"></div><div><x-warehouse.input-label for="plant_size_unit" value="Plant Size Unit" class="mb-2"/><input id="plant_size_unit" name="plant_size_unit" value="{{ old('plant_size_unit',$renewableEnergy->plant_size_unit) }}" class="block w-full rounded-xl border p-3"></div><div><x-warehouse.input-label for="livestock_details" value="Livestock Details (for Biogas)" class="mb-2"/><input id="livestock_details" name="livestock_details" value="{{ old('livestock_details',$renewableEnergy->livestock_details) }}" class="block w-full rounded-xl border p-3"></div><div><x-warehouse.input-label for="plant_start_date" value="Plant Start Date" class="mb-2"/><input id="plant_start_date" name="plant_start_date" type="date" value="{{ old('plant_start_date',$renewableEnergy->plant_start_date) }}" class="block w-full rounded-xl border p-3"></div><div><x-warehouse.input-label for="plant_end_date" value="Plant End Date" class="mb-2"/><input id="plant_end_date" name="plant_end_date" type="date" value="{{ old('plant_end_date',$renewableEnergy->plant_end_date) }}" class="block w-full rounded-xl border p-3"></div><div><x-warehouse.input-label for="document" value="Replace Document / File" class="mb-2"/><input id="document" name="document" type="file" class="block w-full rounded-xl border p-3"></div></div><div class="mt-5"><x-warehouse.input-label for="contribution_condition" value="Plant Contribution / Condition" class="mb-2"/><textarea id="contribution_condition" name="contribution_condition" rows="3" class="block w-full rounded-xl border p-3">{{ old('contribution_condition',$renewableEnergy->contribution_condition) }}</textarea></div><div class="mt-5"><x-warehouse.input-label for="remarks" value="Remarks" class="mb-2"/><textarea id="remarks" name="remarks" rows="3" class="block w-full rounded-xl border p-3">{{ old('remarks',$renewableEnergy->remarks) }}</textarea></div></div>
<div class="flex justify-end gap-3"><a href="{{ route('warehouse.renewable-energy.index') }}" class="rounded-xl border px-5 py-3">Cancel</a><x-loading-submit type="submit" class="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-600 px-5 py-3 font-semibold text-white" icon="save" loading-text="Updating...">Update Entry</x-loading-submit></div></form></div></x-warehouse-layout>


<script>
const setLocationOptions = (id, items) => window.dispatchEvent(new CustomEvent('warehouse-searchable-select-options', { detail: { id, options: (items || []).map(item => ({ value: String(item.id), label: item.en_name || item.name })) } }));
const loadLocationOptions = async (id, url) => { if (!url) return setLocationOptions(id, []); const response = await fetch(url, { headers: { Accept: 'application/json' } }); setLocationOptions(id, response.ok ? (await response.json()) : []); };
window.addEventListener('warehouse-searchable-select-change', async event => { const { id, value } = event.detail; if (id === 'division_id') { await loadLocationOptions('district_id', value ? `{{ url('/warehouse/renewable-energy/geocode/districts') }}/${value}` : null); setLocationOptions('upazila_id', []); setLocationOptions('union_id', []); } if (id === 'district_id') { await loadLocationOptions('upazila_id', value ? `{{ url('/warehouse/renewable-energy/geocode/upazilas') }}/${value}` : null); setLocationOptions('union_id', []); } if (id === 'upazila_id') await loadLocationOptions('union_id', value ? `{{ url('/warehouse/renewable-energy/geocode/unions') }}/${value}` : null); });
</script>

