<x-warehouse-layout title="Renewable Energy">
    @php($isPaginated = $entries instanceof \Illuminate\Pagination\AbstractPaginator)
    <div class="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm">
        <x-warehouse.page-header title="Renewable Energy List" description="Review renewable energy entries recorded by this LSP."><x-slot name="actions"><x-warehouse.button href="{{ route('warehouse.renewable-energy.create') }}" variant="primary" icon="plus" class="rounded-xl px-5 py-3">Add New</x-warehouse.button></x-slot></x-warehouse.page-header>
        <form method="GET" class="border-t border-slate-200 bg-slate-50 px-4 py-4 sm:px-6"><div class="grid gap-4 lg:grid-cols-[minmax(220px,1fr)_180px_180px_130px_auto] lg:items-end"><div><x-warehouse.input-label for="search" value="Search" class="mb-2 text-slate-700" /><input id="search" name="search" value="{{ $search }}" placeholder="Client, phone, type or village" class="block h-11 w-full rounded-xl border border-slate-300 bg-white px-4 text-sm outline-none focus:border-red-500 focus:ring-2 focus:ring-red-500/20"></div><div><x-warehouse.input-label for="from_date" value="Visit Date From" class="mb-2 text-slate-700" /><input id="from_date" type="date" name="from_date" value="{{ $fromDate ?? '' }}" class="block h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm outline-none focus:border-red-500 focus:ring-2 focus:ring-red-500/20"></div><div><x-warehouse.input-label for="to_date" value="Visit Date To" class="mb-2 text-slate-700" /><input id="to_date" type="date" name="to_date" value="{{ $toDate ?? '' }}" class="block h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm outline-none focus:border-red-500 focus:ring-2 focus:ring-red-500/20"></div><div><x-warehouse.input-label for="per_page" value="Show" class="mb-2 text-slate-700" /><select id="per_page" name="per_page" class="block h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm"><option value="10" @selected($perPage === '10')>10</option><option value="25" @selected($perPage === '25')>25</option><option value="50" @selected($perPage === '50')>50</option><option value="100" @selected($perPage === '100')>100</option><option value="all" @selected($perPage === 'all')>All</option></select></div><div class="flex gap-3"><x-loading-submit type="submit" class="inline-flex items-center justify-center gap-2 rounded-xl bg-red-600 px-5 py-3 text-sm font-semibold text-white shadow-sm hover:bg-red-500" icon="funnel" loading-text="Filtering...">Filter</x-loading-submit><x-warehouse.button href="{{ route('warehouse.renewable-energy.index') }}" variant="secondary" class="px-5 py-3" icon="rotate-ccw">Reset</x-warehouse.button></div></div></form>
        <div class="p-4 sm:p-6"><div class="overflow-x-auto"><table class="min-w-[1900px] divide-y divide-slate-200 text-sm"><thead class="bg-emerald-600 text-white"><tr><th class="px-3 py-3 text-left">SL</th><th class="px-3 py-3 text-left">Type</th><th class="px-3 py-3 text-left">Client Name</th><th class="px-3 py-3 text-left">Client Number</th><th class="px-3 py-3 text-left">Visit Date</th><th class="px-3 py-3 text-left">Area</th><th class="px-3 py-3 text-left">Agent</th><th class="px-3 py-3 text-left">Mobile No</th><th class="px-3 py-3 text-left">Division</th><th class="px-3 py-3 text-left">District</th><th class="px-3 py-3 text-left">Upazila</th><th class="px-3 py-3 text-left">Union</th><th class="px-3 py-3 text-left">Ward  Number</th><th class="px-3 py-3 text-left">Village</th><th class="px-3 py-3 text-left">Livestock Details</th><th class="px-3 py-3 text-left">P.O Name</th><th class="px-3 py-3 text-left">Plant Size</th><th class="px-3 py-3 text-left">File</th><th class="px-3 py-3 text-left">Start Date</th><th class="px-3 py-3 text-left">End Date</th><th class="px-3 py-3 text-left">Remarks</th><th class="px-3 py-3 text-left">Action</th></tr></thead><tbody class="divide-y divide-slate-100">
            @forelse($entries as $entry)<tr class="align-top hover:bg-slate-50"><td class="px-3 py-3">{{ $isPaginated ? $entries->firstItem() + $loop->index : $loop->iteration }}</td><td class="px-3 py-3 capitalize">{{ $entry->type }}</td><td class="px-3 py-3 font-semibold">{{ $entry->client_name }}</td><td class="px-3 py-3">{{ $entry->client_number ?: '-' }}</td><td class="px-3 py-3">{{ $entry->visit_date ? \Carbon\Carbon::parse($entry->visit_date)->format('d-m-Y') . ' ' . ($entry->created_at ? \Carbon\Carbon::parse($entry->created_at)->format('h:i A') : '') : '-' }}</td><td class="px-3 py-3">{{ $entry->area?->name ?: $warehouse->name }}</td><td class="px-3 py-3">{{ $entry->agent?->name ?: $warehouseName }}</td><td class="px-3 py-3">{{ $entry->agent?->phone ?: 'N/A' }}</td><td class="px-3 py-3">{{ $entry->division?->name ?: 'N/A' }}</td><td class="px-3 py-3">{{ $entry->district?->name ?: 'N/A' }}</td><td class="px-3 py-3">{{ $entry->upazila?->name ?: 'N/A' }}</td><td class="px-3 py-3">{{ $entry->union?->name ?: 'N/A' }}</td><td class="px-3 py-3">{{ $entry->ward_number ?: 'N/A' }}</td><td class="px-3 py-3">{{ $entry->village ?: 'N/A' }}</td><td class="px-3 py-3">{{ $entry->livestock_details ?: 'N/A' }}</td><td class="px-3 py-3">{{ $entry->po_name ?: 'N/A' }}</td><td class="px-3 py-3 whitespace-nowrap">{{ $entry->plant_size ? $entry->plant_size.' '.($entry->plant_size_unit ?: 'm³') : 'N/A' }}</td><td class="px-3 py-3">@if($entry->document)<a href="{{ asset($entry->document) }}" target="_blank" class="font-semibold text-blue-600 hover:underline"><x-warehouse.icon name="file-text" class="inline-block h-5 w-5" /></a>@else N/A @endif</td><td class="px-3 py-3">{{ $entry->plant_start_date ? date('d-m-Y', strtotime($entry->plant_start_date)) : 'N/A' }}</td><td class="px-3 py-3">{{ $entry->plant_end_date ? date('d-m-Y', strtotime($entry->plant_end_date)) : 'N/A' }}</td><td class="px-3 py-3">{{ $entry->remarks ?: 'N/A' }}</td><td class="px-3 py-3 text-right whitespace-nowrap"><a href="{{ route('warehouse.renewable-energy.edit', $entry) }}" title="Edit entry" aria-label="Edit entry" class="mr-2 inline-flex h-8 w-8 items-center justify-center rounded-lg border border-sky-200 bg-sky-50 text-sky-700 transition hover:bg-sky-100"><x-warehouse.icon name="square-pen" class="h-4 w-4" /></a><form method="POST" action="{{ route('warehouse.renewable-energy.destroy', $entry) }}" class="inline" onsubmit="return confirm('Delete this renewable energy entry?')">@csrf @method('DELETE')<button type="submit" title="Delete entry" aria-label="Delete entry" class="inline-flex h-8 w-8 items-center justify-center rounded-lg border border-rose-200 bg-rose-50 text-rose-600 transition hover:bg-rose-100"><x-warehouse.icon name="trash-2" class="h-4 w-4" /></button></form></td></tr>@empty<tr><td colspan="22" class="px-4 py-12 text-center text-slate-500">No renewable energy entries found.</td></tr>@endforelse
        </tbody></table></div>@if($isPaginated)<div class="mt-4">{{ $entries->onEachSide(1)->links('warehouse-portal.partials.pagination') }}</div>@endif</div>
    </div>
</x-warehouse-layout>







